CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT NOT NULL,
    title TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    location TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT events_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT events_time_order CHECK (end_at > start_at)
);

CREATE INDEX IF NOT EXISTS events_start_at_idx
    ON events (start_at);

CREATE INDEX IF NOT EXISTS events_time_range_idx
    ON events (start_at, end_at);

CREATE INDEX IF NOT EXISTS events_title_trgm_idx
    ON events USING gin (title gin_trgm_ops);

CREATE INDEX IF NOT EXISTS events_location_trgm_idx
    ON events USING gin (location gin_trgm_ops)
    WHERE location IS NOT NULL;

CREATE INDEX IF NOT EXISTS events_description_trgm_idx
    ON events USING gin (description gin_trgm_ops)
    WHERE description IS NOT NULL;

CREATE OR REPLACE FUNCTION events_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS events_touch_updated_at ON events;

CREATE TRIGGER events_touch_updated_at
BEFORE UPDATE ON events
FOR EACH ROW
EXECUTE FUNCTION events_touch_updated_at();
